# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gymestry' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gymestry
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod ‘Firebase/Database’
	pod 'SnapKit'
	pod 'CalendarKit'
	pod 'Firebase/Storage'
	pod 'Realm'
	pod 'RealmSwift'
	pod 'Gifu'
	pod 'Charts'

end
